[package]
name = "collapse_if_slowdown"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "slow_fast"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
